name: 'Validate BPMN process model'
description: 'A reusable GitHub Action for validating BPMN process models'
author: 'Kristoffer Högberg'
inputs:
  bpmn-files-path:
    description: 'The path to the directory containing the BPMN files to validate'
    required: true
  custom-rules-folder:
    description: 'The path to the directory containing custom bpmnlint rules'
    required: true
  bpmnlintrc-path:
    description: 'The path to the .bpmnlintrc configuration file'
    required: true
runs:
  using: 'node'
  main: 'dist/index.js'
  
