name: 'Validate BPMN process model'
description: 'This action validates BPMN process models using bpmnlint'
inputs:
  bpmn-files-path:
    description: 'Path to BPMN files for validation'
    required: true
    default: '.'
  custom-rules-folder:
    description: 'Path to custom rules folder'
    required: true
    default: '.'
  bpmnlintrc-path:
    description: 'Path to .bpmnlintrc configuration file'
    required: true
    default: '.'

runs:
  using: 'node18'
  main: 'main.js'
