name: Validate BPMN process model

on:
  workflow_call:
    inputs:
      bpmn-files-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      - name: Install npm dependencies
        run: npm install -g bpmnlint

      - name: List files in .github/workflows
        run: ls -al .github/workflows

      - name: List files in current directory
        run: ls -al

      - name: Run JavaScript script
        run: node .github/workflows/validate-bpmn.js
        env:
          INPUT_CUSTOM_RULES_FOLDER: ${{ inputs.custom-rules-folder }}
          INPUT_BPMNLINTRC_PATH: ${{ inputs.bpmnlintrc-path }}
          INPUT_BPMN_FILES_PATH: ${{ inputs.bpmn-files-path }}
