name: Validate BPMN process model

on:
  workflow_call:
    inputs:
      bpmn-files-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install bpmnlint
        run: npm install -g bpmnlint
        
      - name: Run custom validation script
        run: |
          node -e "const validationScript = require('./path/to/validation-script.js'); validationScript.copyCustomRules('${{ inputs.custom-rules-folder }}'); validationScript.listAvailableRules(); validationScript.createBpmnlintrcFile('${{ inputs.bpmnlintrc-path }}'); validationScript.runBpmnValidation('${{ inputs.bpmn-files-path }}');"
