name: Validate BPMN process model

on:
  workflow_call:
    inputs:
      bpmn-files-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install bpmnlint
        run: npm install -g bpmnlint
        
      - name: Run custom JavaScript file
        run: node .github/workflows/run-bpmn-validation.js
        env:
          CUSTOM_RULES_FOLDER: ${{ inputs.custom-rules-folder }}
          BPMNLINTRC_PATH: ${{ inputs.bpmnlintrc-path }}

      - name: Run BPMN validation and output result
        run: |
          for file in ${{ inputs.bpmn-files-path }}/*.bpmn; do
            if [ -z "$(bpmnlint "$file")" ]; then
              echo -e "\033[32mNo errors found in $file\033[0m"
            else
              echo -e "\033[31mErrors found in $file:\033[0m"
              bpmnlint "$file" || true
            fi
          done
