name: Validate BPMN process model

on:
  workflow_call:
    inputs:
      bpmn-file-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install bpmnlint
        run: npm install -g bpmnlint
        
      - name: Copy custom rules to bpmnlint/rules folder
        run: |
          cp -r ${{ inputs.custom-rules-folder }}/* /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules/
        working-directory: ${{ github.workspace }}  
        
      - name: List all current rules
        run: ls -al /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules
        
      - name: Read BPMN file content
        run: |
          cat "${{ inputs.bpmn-file-path }}" > bpmn-file-content.bpmn
          
      - name: Read and create .bpmnlintrc file
        run: |
          cat "${{ inputs.bpmnlintrc-path }}" > .bpmnlintrc.txt
          mv .bpmnlintrc.txt .bpmnlintrc

      - name: Run BPMN validation and output result  
        run: bpmnlint bpmn-file-content.bpmn || true		
