name: Validate BPMN process model

on:
  workflow_call:
    inputs:
      bpmn-files-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install bpmnlint
        run: npm install -g bpmnlint
        
      - name: Copy custom rules
        run: node run-bpmn-validation.js copy-rules
        env:
          CUSTOM_RULES_FOLDER: ${{ inputs.custom-rules-folder }}
        working-directory: ${{ github.workspace }}
        
      - name: List all available rules
        run: node run-bpmn-validation.js list-rules
        
      - name: Read and create .bpmnlintrc configuration file
        run: node run-bpmn-validation.js create-lintrc
        env:
          BPMNLINTRC_PATH: ${{ inputs.bpmnlintrc-path }}
        
      - name: Run BPMN validation and output result
        run: node run-bpmn-validation.js run-validation
        env:
          BPMN_FILES_PATH: ${{ inputs.bpmn-files-path }}
